-- TABLE: TBL_AREA
CREATE TABLE TBL_AREA
(
    ID                   NUMERIC(8) NOT NULL PRIMARY KEY,
    NOMBRE               VARCHAR2(60) NOT NULL UNIQUE,
    ABREVIADO            VARCHAR2(60) NOT NULL UNIQUE,
    ESTADO               CHAR(1)   DEFAULT '1',
    USUARIO_CREACION     VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_CREACION       TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    USUARIO_MODIFICACION VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_MODIFICACION   TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)
);

CREATE SEQUENCE SEQ_AREA;

INSERT INTO TBL_AREA(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_AREA.NEXTVAL, 'SISTEMAS', 'SIST');
INSERT INTO TBL_AREA(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_AREA.NEXTVAL, 'TESORERIA', 'TESO');
INSERT INTO TBL_AREA(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_AREA.NEXTVAL, 'GERENCIA GENERAL', 'GGAL');
INSERT INTO TBL_AREA(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_AREA.NEXTVAL, 'FACTURACION', 'FACT');
INSERT INTO TBL_AREA(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_AREA.NEXTVAL, 'VENTAS', 'VENT');
INSERT INTO TBL_AREA(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_AREA.NEXTVAL, 'CONTABILIDAD', 'CONT');
COMMIT;

-- TABLE: TBL_EMPLEADO
CREATE TABLE TBL_EMPLEADO
(
    ID                   NUMERIC(8) NOT NULL PRIMARY KEY,
    NOMBRES              VARCHAR2(60) NOT NULL,
    APELLIDOS            VARCHAR2(400) NULL,
    CORREO               VARCHAR2(400) NULL,
    DIRECCION            VARCHAR2(400) NULL,
    TELEFONO             VARCHAR2(400) NULL,
    AREA_ID              NUMERIC(8),
    ESTADO               CHAR(1)   DEFAULT '1',
    USUARIO_CREACION     VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_CREACION       TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    USUARIO_MODIFICACION VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_MODIFICACION   TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    FOREIGN KEY (AREA_ID) REFERENCES TBL_AREA (ID)
);

CREATE SEQUENCE SEQ_EMPLEADO;

INSERT INTO TBL_EMPLEADO (ID, NOMBRES, APELLIDOS, CORREO, DIRECCION, TELEFONO)
VALUES (SEQ_EMPLEADO.NEXTVAL, 'MARCO', 'LOPEZ', 'MARCO.LOPEZ@EXAMPLE.COM', 'SJM', '555-5555');
INSERT INTO TBL_EMPLEADO (ID, NOMBRES, APELLIDOS, CORREO, DIRECCION, TELEFONO)
VALUES (SEQ_EMPLEADO.NEXTVAL, 'JOHN', 'DOE', 'JOHN.DOE@EXAMPLE.COM', 'NEW YORK', '555-5555');
INSERT INTO TBL_EMPLEADO (ID, NOMBRES, APELLIDOS, CORREO, DIRECCION, TELEFONO)
VALUES (SEQ_EMPLEADO.NEXTVAL, 'JUAN', 'PEREZ', 'JUAN.PEREZ@EXAMPLE.COM', 'MIRAFLORES', '555-5555');
COMMIT;

-- TABLE: TBL_CENTRO_COSTO
CREATE TABLE TBL_CENTRO_COSTO
(
    ID                   NUMERIC(8) NOT NULL PRIMARY KEY,
    NOMBRE               VARCHAR2(60) NOT NULL UNIQUE,
    ABREVIADO            VARCHAR2(60) NOT NULL UNIQUE,
    ESTADO               CHAR(1)   DEFAULT '1',
    USUARIO_CREACION     VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_CREACION       TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    USUARIO_MODIFICACION VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_MODIFICACION   TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)
);

CREATE SEQUENCE SEQ_CENTRO_COSTO;

INSERT INTO TBL_CENTRO_COSTO(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_CENTRO_COSTO.NEXTVAL, 'SISTEMAS', 'AS');
INSERT INTO TBL_CENTRO_COSTO(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_CENTRO_COSTO.NEXTVAL, 'RRHH', 'RH');
INSERT INTO TBL_CENTRO_COSTO(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_CENTRO_COSTO.NEXTVAL, 'ALMACEN', 'ALM');
COMMIT;

-- TABLE: TBL_REQUERIMIENTO
CREATE TABLE TBL_BANCO
(
    ID                   NUMERIC(8) NOT NULL PRIMARY KEY,
    NOMBRE               VARCHAR2(60) NOT NULL UNIQUE,
    ABREVIADO            VARCHAR2(60) NOT NULL UNIQUE,
    ESTADO               CHAR(1)   DEFAULT '1',
    USUARIO_CREACION     VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_CREACION       TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    USUARIO_MODIFICACION VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_MODIFICACION   TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP)
);

CREATE SEQUENCE SEQ_BANCO;

INSERT INTO TBL_BANCO(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_BANCO.NEXTVAL, 'BANCO DE CREDITO DEL PERU', 'BCP');
INSERT INTO TBL_BANCO(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_BANCO.NEXTVAL, 'BANCO INTERBANK', 'IBK');
INSERT INTO TBL_BANCO(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_BANCO.NEXTVAL, 'BANCO BBVA', 'BBVA');
INSERT INTO TBL_BANCO(ID, NOMBRE, ABREVIADO)
VALUES (SEQ_BANCO.NEXTVAL, 'BANCO SCOTIABANK', 'SBA');
COMMIT;

-- TABLE: TBL_REQUERIMIENTO
CREATE TABLE TBL_REQUERIMIENTO
(
    ID                         NUMERIC(8) NOT NULL PRIMARY KEY,
    CODIGO                     VARCHAR2(60) NOT NULL UNIQUE,
    FECHA                      DATE,
    AREA_ID                    NUMERIC(8),
    CENTRO_COSTO_ID            NUMERIC(8),
    SOLICITANTE_ID             NUMERIC(8),
    FECHA_REQUERIDA            DATE,
    PRIORIDAD                  VARCHAR2(50),
    ASUNTO                     VARCHAR2(250),
    SUSTENTO                   VARCHAR2(500),
    TIPO_PAGO                  VARCHAR2(50),
    BANCO_ID                   NUMERIC(8),
    CUENTA                     VARCHAR2(100),
    FECHA_GESTION_COMPRA       DATE,
    FECHA_ENTREGA_AREA         DATE,
    FECHA_APROBACION_EVALUADOR DATE,
    EVALUADOR_ID               NUMERIC(8),
    MONEDA                     VARCHAR2(20),
    SITUACION                  VARCHAR2(50),
    FECHA_ANULACION            DATE,
    ANULADOR_ID                NUMERIC(8),
    FECHA_CIERRE               DATE,
    CERRADOR_ID                NUMERIC(8),
    ESTADO                     CHAR(1)   DEFAULT '1',
    USUARIO_CREACION           VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_CREACION             TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    USUARIO_MODIFICACION       VARCHAR2(50) DEFAULT 'SYSTEM',
    FECHA_MODIFICACION         TIMESTAMP DEFAULT SYS_EXTRACT_UTC(SYSTIMESTAMP),
    FOREIGN KEY (AREA_ID) REFERENCES TBL_AREA (ID),
    FOREIGN KEY (CENTRO_COSTO_ID) REFERENCES TBL_CENTRO_COSTO (ID),
    FOREIGN KEY (SOLICITANTE_ID) REFERENCES TBL_EMPLEADO (ID),
    FOREIGN KEY (BANCO_ID) REFERENCES TBL_BANCO (ID)
);

CREATE SEQUENCE SEQ_REQUERIMIENTO;

-- INSERT INTO TBL_REQUERIMIENTO(ID, CODIGO, FECHA, AREA_ID, CENTRO_COSTO_ID, EMPLEADO_ID, FECHA_REQUERIDA)
-- VALUES (SEQ_REQUERIMIENTO.NEXTVAL, '7f6b70a5-0221-4d8d-b9b9-874e06f83dfe', CURRENT_DATE, 1, 1, 1, TO_DATE('28/01/2023', 'DD/MM/YYYY'));

